export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES_OF_PRODUCT = "GET_CATEGORIES_OF_PRODUCT";
export const GET_PRODUCTS_OF_CATEGORY = "GET_PRODUCTS_OF_CATEGORY";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const SEARCH_BY_KEYWORD = "SEARCH_BY_KEYWORD";
export const ADD_CATEGORY_TO_PRODUCT = "ADD_CATEGORY_TO_PRODUCT";
export const ADD_CATEGORY_TO_PRODUCT_BY_NAME =
  "ADD_CATEGORY_TO_PRODUCT_BY_NAME";
export const REMOVE_CATEGORY_FROM_PRODUCT = "REMOVE_CATEGORY_FROM_PRODUCT";
// GET A USUARIOS CREADOS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const NEW_USERS = "NEW_USERS";
export const ADD_ITEM_TO_GUEST_CART = "ADD_ITEM_TO_GUEST_CART";
export const REMOVE_ITEM_FROM_GUEST_CART = "REMOVE_ITEM_TO_GUEST_CART";
/* export const RELOAD_CATEGORIES_OF_PRODUCT = "RELOAD_CATEGORIES_OF_PRODUCT"; */
//CARRITO
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const GET_ONLY_USER = "GET_ONLY_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const GET_ALL_ITEMS_TO_CART = "GET_ALL_ITEMS_TO_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const MODIFY_QUANTITY_ITEM = "MODIFY_QUANTITY_ITEM";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const GET_REVIEWS_OF_PRODUCT = "GET_ALL_REVIEWS_OF_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW"
export const PROMOTE_USER = "PROMOTE_USER";
//PASSWORD
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CURRENT_USER = "CURRENT_USER";
export const SEND_TEMPCART_TO_DATABASE = "SEND_TEMPCART_TO_DATABASE";
//QUESTIONS
export const GET_ALL_QUESTION = "GET_ALL_QUESTION";
export const GET_PRODUCT_OF_ANSWER = "GET_PRODUCT_OF_ANSWER";
